name: Run Selenium On GitHub Action

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Installing dependencies
        run: |
          pip install pandas
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          pip install psycopg2
          pip install glob
          pip install supabase
          pip install webdriver-manager

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Python script
        run: python keepa_product_finder.py

      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "GitHub Actions Results added"
          git push
