name: Run Selenium On GitHub Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8,17 * * *'  # Run every day at 8 AM and 5 PM

jobs:
  scrape1:
    runs-on: ubuntu-latest
    timeout-minutes: 600000
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Installing dependencies
        run: |
          pip install pandas
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          pip install psycopg2
          pip install supabase
          pip install webdriver-manager

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run Python script to check if update is needed
        id: check_update
        run: |
          python check_update_script.py  # Replace with your script to check the date
          echo "::set-output name=update_needed::$?"  # $? is the exit code of the last command

      - name: Running the Python script (conditionally)
        if: steps.check_update.outputs.update_needed == '0'  # '0' indicates success, i.e., today's date
        run: python keepa_best_seller.py

  scrape2:
    runs-on: ubuntu-latest
    timeout-minutes: 600000
    needs: scrape1  # Wait for scrape1 to complete
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Installing dependencies
        run: |
          pip install pandas
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay
          pip install psycopg2
          pip install supabase
          pip install webdriver-manager

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Run Python script to check if update is needed
        id: check_update
        run: |
          python check_update_script.py  # Replace with your script to check the date
          echo "::set-output name=update_needed::$?"  # $? is the exit code of the last command

      - name: Running the Keepa script
        run: python keepa_product_finder.py
